version: '3'
services:
  db:
    container_name: dbpostgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRESQL_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  server:
    container_name: eventsserver
    image: eventsserver
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8000:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - STRING_DATABASE_TEST_URL=${STRING_DATABASE_TEST_URL}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - EVENTS_EMAIL_USERNAME=${EVENTS_EMAIL_USERNAME}
      - EVENTS_EMAIL_PASSWORD=${EVENTS_EMAIL_PASSWORD}
      - FACEBOOK_APP_ID=${FACEBOOK_APP_ID}
      - FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}
