version: 2
jobs:
  build:
    
    working_directory: ~/events-java

    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: samuel
          POSTGRES_DB: eventappdbtest

    steps:

      - checkout

      - restore_cache:
          key: events-java-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: events-java-{{ checksum "pom.xml" }}
      
      - run: mvn test